name: Publish package

on: [push]

jobs:
  build-xfce4-docklike-plugin:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: sudo apt update && sudo apt-get install build-essential dpkg binutils intltool xfce4-dev-tools xorg-dev libglib2.0-dev libgtk-3-dev libwnck-3-dev libxfce4ui-2-dev libxfce4panel-2.0-dev

    - name: Build
      run: |
        mkdir usr
        ./configure --prefix=/home/runner/work/xfce4-docklike-plugin/xfce4-docklike-plugin/usr
        make
        make install

    - name: Build Deb File for Ubuntu
      run: |
        mkdir xfce4-docklike-plugin
        cp -R DEBIAN xfce4-docklike-plugin
        cp -R usr xfce4-docklike-plugin
        dpkg -b xfce4-docklike-plugin

    - name: Automatic Release
      uses: marvinpinto/action-automatic-releases@latest
      with: 
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "0.4.1"
        prerelease: false
        title: "Latest Build - 0.4.1"
        files: |
          *.deb