name: Publish package

on:
  push:
    paths:
      - .github/workflows/publish.yml
  workflow_dispatch:

env:
  version: "0.5.0"

jobs:
  build-xfce4-docklike-plugin:
    runs-on: ubuntu-latest
    container:
      image: debian:sid
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: apt update && DEBIAN_FRONTEND=noninteractive apt-get install meson wget tar build-essential dpkg binutils intltool xfce4-dev-tools xorg-dev libxfce4windowing-0-dev libglib2.0-dev libgtk-3-dev libwnck-3-dev libxfce4ui-2-dev libxfce4panel-2.0-dev -y

    - name: Build
      run: |
        wget https://archive.xfce.org/src/panel-plugins/xfce4-docklike-plugin/0.5/xfce4-docklike-plugin-${{ env.version }}.tar.xz
        tar -xvf xfce4-docklike-plugin-${{ env.version }}.tar.xz
        cd xfce4-docklike-plugin-${{ env.version }}
        meson setup --prefix=/usr build
        meson configure build -D enable-apport=false -D production-release=true
        meson compile -C build
        meson install -C build --destdir=xfce4-docklike-plugin

    - name: Upload archive
      uses: actions/upload-artifact@v4
      with:
        name: xfce4-docklike-plugin
        path: /__w/xfce4-docklike-plugin/xfce4-docklike-plugin/xfce4-docklike-plugin-${{ env.version }}/*
        retention-days: 3

    - name: Build Deb File
      run: |
        cd xfce4-docklike-plugin-${{ env.version }}
        mkdir -p xfce4-docklike-plugin/DEBIAN
        cp -R /__w/xfce4-docklike-plugin/xfce4-docklike-plugin/DEBIAN/* xfce4-docklike-plugin/DEBIAN/
        dpkg -b xfce4-docklike-plugin

    - name: Automatic Release
      uses: marvinpinto/action-automatic-releases@latest
      with: 
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ env.version }}
        prerelease: false
        title:  "Latest Build ${{ env.version }}"
        files: |
          xfce4-docklike-plugin-${{ env.version }}/*.deb
